name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build samples
        run: yarn build:samples
      - name: Build
        run: yarn build
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: yarn interaction --workers=1
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-test-results
          path: tests/interaction/test-results/
          retention-days: 14
          if-no-files-found: ignore
